### ISSUE TITLE
Support for calling arbitrary functions on minions

### ISSUE THREAD

**Issue by rmc3** [jbussdieker/ruby-salt-api#2]
Is there currently the ability to call an arbitrary function on a minion or group of minions? e.g., the equivalent of `salt '*' test.ping`

From a quick review of the source, it doesn't look like this has been implemented.

**Comment by jbussdieker** [comment]
This feature was just added with 3b228200f709ba553312773b8b26f31335ea92e8. See the README.md for an example.
